name: fuzz4all
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - annotated-types==0.6.0
      - anyio==4.2.0
      - beautifulsoup4==4.12.2
      - bs4==0.0.1
      - certifi==2023.11.17
      - cffi==1.16.0
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - coverage==7.2.7
      - cryptography==41.0.7
      - cycler==0.12.1
      - dill==0.3.7
      - distlib==0.3.8
      - distro==1.9.0
      - exceptiongroup==1.2.0
      - fastcov==1.14
      - filelock==3.13.1
      - fonttools==4.47.0
      - fsspec==2023.12.2
      - genhtml==2.0.0
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.1
      - identify==2.5.33
      - idna==3.6
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - lxml==4.9.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - nodeenv==1.8.0
      - ntlm-auth==1.5.0
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.6.1
      - packaging==23.2
      - pandas==2.0.3
      - pbr==6.0.0
      - pillow==10.1.0
      - platformdirs==4.1.0
      - ply==3.11
      - pre-commit==3.6.0
      - psutil==5.9.7
      - pycparser==2.21
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - qiskit==0.43.1
      - qiskit-aer==0.12.0
      - qiskit-ibmq-provider==0.20.2
      - qiskit-terra==0.24.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-ntlm==1.1.0
      - rich==13.7.0
      - rustworkx==0.13.2
      - safetensors==0.4.1
      - scipy==1.11.4
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stevedore==5.1.0
      - symengine==0.9.2
      - sympy==1.12
      - tiktoken==0.5.2
      - tokenizers==0.15.0
      - toml==0.10.2
      - torch==2.1.2
      - tqdm==4.66.1
      - transformers==4.36.2
      - triton==2.1.0
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - virtualenv==20.25.0
      - websocket-client==1.7.0
      - websockets==12.0
